### ISSUE TITLE
redgifs profile ripper not working

### ISSUE THREAD

**Issue by terminalwhoami** [ripmeapp2/ripme#105] opened 2022-08-04 22:37 UTC
* Ripme version: 2.1.2
* Java version: openjdk version "11.0.15" 2022-04-19 LTS
OpenJDK Runtime Environment Microsoft-32930 (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM Microsoft-32930 (build 11.0.15+10-LTS, mixed mode)
* Operating system: Microsoft Windows [Version 10.0.19044.1826]
* Exact URL you were trying to rip when the problem occurred: any red gifs user profile
* Please include any additional information about how to reproduce the problem: go to red gifs user profile, try to download it

## Expected Behavior

Profile gets downloaded

## Actual Behavior

Failed to load https://api.redgifs.com/v1/users/<profile>/gfycats?count=100 after 5 attempts

**Comment by soloturn** [comment] 2022-12-25 15:40
duplicate of #108

**Closed by soloturn** 2022-12-25 15:40 UTC
