### ISSUE TITLE
Possible Instagram issue?

### ISSUE THREAD

**Issue by chibifibi** [ripmeapp2/ripme#100] opened 2022-07-23 15:31 UTC
* Ripme version: v1.7.95
* Java version:  Java 8 Update 181
* Operating system:  Windows 10 Pro 10.0.19044

* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/hapatime/?hl=en
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

I thought it would download, as it had already successfully done so with some Twitter profiles. It also correctly detected the Instagram profile, so I thought it would just work.

## Actual Behavior

Log:
Downloading https://www.instagram.com/hapatime/?hl=en
Rip complete, saved to G:\+rips\instagram_hapatime
name:1:0 Expected an operand but found <
<!DOCTYPE html>
^

**Comment by soloturn** [comment] 2022-10-08 19:12
duplicate of #63.

**Closed by soloturn** 2022-10-08 19:12 UTC
