### ISSUE TITLE
Erome doesn't work properly 

### ISSUE THREAD

**Issue by elonnotmusk** [ripmeapp2/ripme#70] opened 2022-02-23 19:14 UTC
* Ripme version: 2.0.4
* Java version: 8 321
* Operating system: WINDOWS 10
 These works are still illegal in many places including much of America -->
[* Exact URL you were trying to rip when the problem occurred:](https://www.erome.com/a/whUlLCU4)
* Please include any additional information about how to reproduce the problem: It doesnt' download png images, and same for video, mp4 files are corrupted when it's downloaded, it does download like one or two videos but the others no
Also some files don't download at all ( mp4 and png files )
Edit:
The dowloaded videos are corrupted, videos of 34 sec plays only 4 sec. and some videos says failed to download

**Comment by soloturn** [comment] 2022-12-25 15:39
duplicate of #123 (as more info is in the other ticket).

**Closed by soloturn** 2022-12-25 15:39 UTC
