### ISSUE TITLE
Instagram ripper only ripping first 15 images or so.

### ISSUE THREAD

**Issue by SquaredDog** [ripmeapp2/ripme#44] opened 2021-07-05 01:45 UTC
* Ripme version: Latest
* Java version:  build Version 8 Update 291 1.8.0_291-b10
* Operating system:  Windows

* Exact URL you were trying to rip when the problem occurred: https://www.instagram.com/celinechenn_/
* Please include any additional information about how to reproduce the problem:

## Expected Behavior

Downloading of all images

## Actual Behavior

Only downloading the first 15 images (1 or 2 pages)

**Comment by soloturn** [comment] 2021-07-10 06:58
is this a duplicate of #32 ?

**Comment by terminalwhoami** [comment] 2021-11-22 20:05
Looks like this issue still exists in the latest version of this fork, including when using a session id

**Comment by soloturn** [comment] 2023-10-14 12:52
lets close this, until somebody opens it for a current version or provides a pull request.

**Closed by soloturn** 2023-10-14 12:52 UTC
