### ISSUE TITLE
Erome Pictures Not Downloading

### ISSUE THREAD

**Issue by Dafrankster** [ripmeapp2/ripme#109] opened 2022-09-27 02:58 UTC
* Ripme version: 2.0.1 & 2.1.2
* Java version: JAVA 11
* Operating system: WIN10
* Exact URL you were trying to rip when the problem occurred: https://www.erome.com/a/***
* Please include any additional information about how to reproduce the problem:

Any erome album with pictures will not rip. I deleted local app data files to provide a clean instance. 
I was getting: 'other' has different root before deleting the rip.properties file and URL history on 2.1.2.
Version 2.0.1 was working just fine until recently. 

## Expected Behavior

Rip the entire album. 

## Actual Behavior

Only rips videos, pictures are not being downloaded.

**Comment by soloturn** [comment] 2022-10-09 10:30
duplicate of #70

**Closed by soloturn** 2022-10-09 10:30 UTC

**Comment by Dafrankster** [comment] 2022-11-04 01:19
To clarify, the videos from an album will rip perfectly fine. It will skip over downloading any pictures though.
