### ISSUE TITLE
Reddit problem

### ISSUE THREAD

**Issue by CashOver** [ripmeapp2/ripme#80] opened 2022-04-05 22:06 UTC
I would like to let you know that you are having a problem with the download system, because every time you download large content, stop all the time in the middle or even at the beginning of the download progress, I would like to know if you could fix this problem.

**Comment by soloturn** [comment] 2022-04-09 08:18
maybe duplicate of #75. if not please reopen with more details.

**Closed by soloturn** 2022-04-09 08:18 UTC
