### ISSUE TITLE
API Error - redgifts

### ISSUE THREAD

**Issue by medledan** [ripmeapp2/ripme#190] opened 2024-06-04 16:36 UTC
* Ripme version: 2.1.9.7
* Java version: 
* Operating system:  Windows 11

## Expected Behavior
Ripping from reddit subs. Have been getting tons of API errors from redgifs.

## Actual Behavior
https://api.redgifs.com/v2/gifs/profusewiltedagama/files/ProfuseWiltedAgama-silent.mp4 : Non-retriable status code 403 while downloading https://api.redgifs.com/v2/gifs/profusewiltedagama/files/ProfuseWiltedAgama-silent.mp4
https://api.redgifs.com/v2/gifs/brightcapitaltrex/files/BrightCapitalTrex-silent.mp4 : Non-retriable status code 403 while downloading https://api.redgifs.com/v2/gifs/brightcapitaltrex/files/BrightCapitalTrex-silent.mp4
https://api.redgifs.com/v2/gifs/assuredwarlikespittlebug/files/AssuredWarlikeSpittlebug-silent.mp4 : Non-retriable status code 403 while downloading https://api.redgifs.com/v2/gifs/assuredwarlikespittlebug/files/AssuredWarlikeSpittlebug-silent.mp4
https://api.redgifs.com/v2/gifs/qualifiedsurprisedsablefish/files/QualifiedSurprisedSablefish-silent.mp4 : Non-retriable status code 403 while downloading https://api.redgifs.com/v2/gifs/qualifiedsurprisedsablefish/files/QualifiedSurprisedSablefish-silent.mp4
https://api.redgifs.com/v2/gifs/gleamingsparklinggoat/files/GleamingSparklingGoat-silent.mp4 : Non-retriable status code 403 while downloading https://api.redgifs.com/v2/gifs/gleamingsparklinggoat/files/GleamingSparklingGoat-silent.mp4
https://api.redgifs.com/v2/gifs/simpleagitateddegu/files/SimpleAgitatedDegu-silent.mp4 : Non-retriable status code 403 while downloading https://api.redgifs.com/v2/gifs/simpleagitateddegu/files/SimpleAgitatedDegu-silent.mp4
https://api.redgifs.com/v2/gifs/ultimateinnocentcockatiel/files/UltimateInnocentCockatiel-silent.mp4 : Non-retriable status code 403 while downloading https://api.redgifs.com/v2/gifs/ultimateinnocentcockatiel/files/UltimateInnocentCockatiel-silent.mp4

**Comment by samt108** [comment] 2024-08-16 11:15
Duplicate of #180 

But yes, it's an issue. I came here to report the problem as well.

**Closed** 2024-12-29 09:23 UTC
